apiVersion: apps/v1
kind: Deployment
metadata:
  name: octopub-audit-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: auditservice
  template:
    metadata:
      labels:
        component: auditservice
    spec:
      containers:
        - name: auditservice
          image: octopussamples/octopub-audit-microservice-mysql
          ports:
            - name: http-audit
              containerPort: 10000
          env:
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: octopub-database-credentials
                  key: database-password
            - name: DATABASE_HOSTNAME
              value: "db01.harrisonmeister"
            - name: DATABASE_PORT
              value: "3306"
            - name: DATABASE_NAME
              value: "octopub_Development"
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: octopub-database-credentials
                  key: database-user
            - name: MIGRATE_AT_START
              value: "false"
            - name: COGNITO_DISABLE_AUTH
              value: "true"