---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: database-credentials
  namespace: production
spec:
  encryptedData:
    database-password: AgCcyR5EPNxGinzbPfv4EHmL3jK43xCeSYj6q+oZIxqfK0G9+Y3IuU0WoYIzrlais7gQkspDktfanj2bHqTqPF36UaqHBHMN7E6dUxCZusSZkUtgEGU4aal8CE6FYXwT0n5B2gLIUfSIKfpuGlhWCnUMyWxk64lHktFc3qArcJ7mKbkZ4imSMBmSSpwzME4un3QMH4qEsY9P9ILMr8zOGM/LwgxCLcQsTjTCFD8W9laYS+SMZlfC/7Bwqh/4/b6gkwLadrRiI5VhXHnI9NELTi0wzf2xKiH4W+u4cz2Exx8doF5HK2Yf4agm6SZ5n41uny8EC5jo3lxiqpTKs7C6B/AWyo200aginxhx+H03bk0eWesRWx3U+1PJZjjj/ey3+pX6XdOa+/Rk/GPWdZyOAuDQPKw3EzANYoLD5ZtjghDQXl9DhC/j7doBRssuNN1RSvrf6I3EKgjQ/ypubPuH+JFsTujEIu3xAwSwnc3vwEN2yJFU3tNIAhqf9H0vjc/NMmrI067KLj7zq3RlsyUGNnZwzzyvxbG87mnBKMcffBj4APlAowel/U2tBTvFesuKHn4asFlTPTV+RQUhnuR/o74USTjJHIsRqMmmXZyUlEJx3AUxJvCkPVXASSDVtqvWdNOuFMSjtZ50ooLkUVXwLClYmvzCQfrAEBBFBYbjVbbVlmJn7V0Gvbjfcv8PC1QblT2xJN+dnDxAxQ==
    database-user: AgDUuvTN2sG2Q7qX9y6V5nhOJN7YzCysmoXhrPjTUnsgxkOgtW2Dum7NJxZQsSS7jwo9J8Uio7saXES72nz2Q5TtM748sS42ALj8oVziGEnmPTaJZySYibEpEhfwX7zgICFDZ93IxxGPP+wBzZL6UxhFsY2bILbB8amgTOdyOzz34yx2ptWQYbz3+XpPx62Li+BuJ40XWjyJBPJQu3C1Kj8qQTIl1s5MZe2wya2y1cdWHoMlQbJfLmmKS+wwTYzrOfL8B1RLgxaabE3ig0GSzHNX5hbvE1R2tFdeSHPGAqq90gbLX9z/71Ih41Tsm5Xr5x5O9N2VDfU6v/xwWH98LdwD0Yd9Nc77s7hymQr4nMtwPbyREO7LNnsNTd0SHH28iVFuVPcBNSLZdGIit7obdcYGdVV4jE5sL95YOiyZOF3eELuAd1m+otol8q/SRK4yt1sPzoKxijdf1JAX5sxYPdJavDn9Y3eGLKrmBBxpG3qqhJroOW0Y68oFy5SIrROIJij6/9MFmfkIk6cnKqagQx4/SWDRHrUSkpoa0qrdCb2Auyo06F5MqGntq0BJv3VEK9jEAYWqxHOr+I6R8neF/wpoMiAKRpGb1UqVM36xJTeeI1gcDiBWVukmzmY3W3SkjKW9scsFnwvFGki29L/vanliVMO9l5mjbDmW0v+Lqg7Okhqo9mNmYBSKYo56A6ciEWX4GH1S9w==
  template:
    metadata:
      creationTimestamp: null
      name: database-credentials
      namespace: production
