---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: database-credentials
  namespace: production
spec:
  encryptedData:
    database-password: AgAUE2xnMTC1YLPBl42VQ2Hlosf4jo2kpAFNqq2f3/oXU+z7qoGnj+aA024gqBnGd6Hhk9EKwXuN5iXx1/90D/Vl3FnLEp+lZMmSpdIEgO5Z1SpqukLo4Y+8f/O94fUWw9p9w6oyO/HAR5WybnAsRq6Sxpv/UAvId1TrrIMI5sCwQHtHammsgEVdJZ73G/6LAWJm6bJ+4ALrlYIK+QH3HxgJDKySRsp2eT52aYKGrEwpZ42eolLtc720FOrRiay4UHqjq3Q7FWof3RC2BXnzhqABB3VoXXWxU5H6Hrma1KSgiEpjF1azdW6fdRm6V0NZF2XADJGlPzpw643aOSwnf8rEU0JLpkpQupVGegwFBSep+Nxlqlzm+yEr7yXhqJ3Cxg2LE/7HCwOpL/3MRq2wSgcDUG8ASNQnTcVUf0l+l7fX8vyQF4TRu5Lhi/Jfvrpxxbn1qt477gCNPu9XDeo4CSNbJQYiB5qV3RpPyk9x2IHZntKYAggFVGMZ6oZz2gZ6zTJE8QZ6HVU/Er/DKbB02FVTmCHWF/5dwfMQdxs0w8vNTh+r5Gsqm66gqGgIxuYH237GJb/Kx5/o1v2Y4nTtUmhkmHbcKp91841orKXs+ndW9Qql4jn1We6/bCayBZeHc+PCY4UmyT+q+TfU7mAkJQDjW/DmZL0RafKmRMP1JgRkDGDJQy153DBT5iHm3hz8bSnXd+aW2Gybx9gncOs=
    database-user: AgCNTaF8oT6GvoB9x5chp/CFQ5IJhJDydCCM2J4COHyN76dnVhvhry+HmrT9kL2mWNwP6X/OFwqxkcdvP9QeraXk/2fgfMmq47xcYxX/hoFXfPKQXvHLN/G2IN3bGIYaOuPFy7OkpM0ZQYdXieWD6Acgil+Igz/mxBkcIcxsyE03bgs9qVWD7g/DS9cBr8tdIKdiDck/BbzYvhxfjO/jv2l0gMdFH3suqnANpzYgWPol5hyzeafaCnWqIxioo8WmqQcTVxx6B00roOWL+5vMh+/O28z0RGFv7UHm85QnfeAHFME+d5UvzxHBebE4kqjf3vZzseEvhaMpG7UjOiVth1ZrgRzE+Un86EK1lJFUi1Gk1srf2cEr0eWWEuP6weKE/CnGCDCOKZbw+z8A2IblP2Z5dtmyVePjQC4gtqW0DO8PXMrlJVvDbdRJE+63d+jK+57/K50eNds/1zs7JMm5V0BBfW+v9TFdgPD01R+v67RRwxlb273hTvF4tLbYTbaD9xOtve5ycZl3g6VH0MjHkndWjs4VQ2l35Kd45jfL0tcarrKk7IfjiYMCCMi9zcllcVkkAza+dwGitwiUMUcPUQo8hP4ikAYITGjyGblnp72HypbtErae0NEgp1ezPqWtns7AFa687B1XPfMAmvSq5SBnbfsGqjxvvUiLWTDncnP3a8VlNWuOTY83x3valJrqPW3XVrxr
  template:
    metadata:
      creationTimestamp: null
      name: database-credentials
      namespace: production
