---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: octopub-database-credentials
  namespace: production
spec:
  encryptedData:
    database-password: AgBHdcbW1urPdkH1ZBmPxDVqHNHmMmVe7n3VofU78bfvaWIkzsXz2NGtshfR7VjSeX8L55oMWDbQgET81TB1G+KfidyLgt3WRMWnD/JdkdVvwPnAHpbvJjtHAIYAZiVC0MKtdsgbVEH/iTKgPtlckSG5CSwbzLB1kpJ/k2i8yDSr/n0bLW4VGwjNKcL+aHBrr1xzwtu3wbIJnpgD15e42NyB3WuaUGkW1EL0Jgp0t47zRV3t5p1wUb+nu97Ek0kJeMCPDRYwqN7zb0SbEglcr0y4UUV82QKkaaoOfsy9y7hqTVoYhXmZvM33QN4VwBEVsiJBq9dnVo3XAaBhXxF3M6fTJB/8JZn92VFeHHRRyVK5DR2HuhCBweJUoZM/23gl8F3Pu+evl9634dLt5RKNw3qrEoSmxq/iR6Az7PAnD/W19CLsv+dvRcOL/Wt/UFx1JORAo8MNZwNtm7vBr9O5pJM5JaeC8SAdZKwOI8TaQfrLFwi11k7dOXpgNvDAHWemhPXLHv7B7nQFMkI7RRdQU/Ns/T2sqYkph3C47BJRwETAgKthdLzymqKM68MOmAwkakcmLbB81Uppe0F3XSrh+9VxBB2A8vbk8F1QkLfYsSE/Q8rYuTYxZHwWBzz0SgQIti2uRDc2cOiiiwoL56xgkDGaK6WFkCXwhwqjIh1GfIzraifMAeDlmeqSy3ledCDv67KB1YaVltFChQ==
    database-user: AgBHe6U57ij5/DsNIoIp3bhFb7nPDL2ROUpEjjL4hRgINHLEVgXOXlEvWwBGNmdBw+FVEzIIBGTeIZ82IosSK5nPc8Oy3a5dqMcnQtNHqjwzdJrQKlNYz75r6bbzn5gZk7G3bFfvSdxBJEMz+EUaspVbC3VKbUlFcSA4NX7uCszIrSCNdCaCIu1WG4dA3zvmM6MPZzM8ViVJfAJ50cs/7m1tKWea6yEkAJWZAE/iZLvTYCP7Ty1IHjkKifVDAKfuQRVT9a/F9O1mFyqFdYjm1Dklof8I1T6Xk6PZ+w2h8kuI5bPuEh7o62eT1rWlv91xhhxF0MpKzytXVXzJYZchzo24toBg2yBFxHBwrRY4RPaP3+YhEjfm934aTZXlGJ1LZ8bfG/oYrwJ+SvT36BqFjVCJFeJxnkIxZYqi7GmUh0rLdnuIhvOOnLVEMM/+iVz/yrCiIuQRu4Nns59iVmEEuYGQHztLwj5p/4y6RvCtODJWFeS3ad2ZW9KWJTgvLw1XoUt9VDF5ED7RbdB0o1+vGPplkqRNEgOLMCoLCyrl4YW90+6ABltPynaBGfCtXFtSFpwKenWY84txjY/jErsK+CnQ5TErznTX81rzrKJFNgc0lEBOKlBmW0LnupTkWiXqxY4tK3+SUEZkNVLC2T07vJaBWnT7seWYg+l1ALKfQDTouvQtER9UGeXEvqTalSJLQ8mWkDPn9g==
  template:
    metadata:
      creationTimestamp: null
      name: octopub-database-credentials
      namespace: production
