---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: database-credentials
  namespace: production
spec:
  encryptedData:
    database-password: AgBLfR/DkFYJcQAzhWcG0LvwEENZFoBqk4VRwfW1WU5VOoCRp9+l0wq97L/U1qrGvbSEg12FKASQmpJ5NEt9JXIgRrl21TqfYoHRwMcqy6KPLvgwpZHyao5289aVFCXWSf6CGS46VxJ+XfRlHRXHTKW/1KDYjxwvRF+/Q6NpYHScynbiux0iC6he2J4Y6pe0BVAA3qmIRUHfHGaC6DwHBiINLIpSz4jUa3k7GNjv5g5p0EbCFBveYVm21+XVkrGf9NRl3yeg6y4WiAXcTk4tH3LMjGiIC2ErByA46UdBZHjYjahrlemxbtyMW2KY36vBA2GRY1/5vPRL9WvGruuCLjvHlVn/M15jGLc3qZS5dL5QudPdLECEXwl8fYxk2Cx5KIiN5Yu1O5/3mznvqfr/ZRUQ7ZcrHUL+tiNlf3BQR+3uKNdgau3L9R4DUxC/qXNo49RCKFAg25IOlrHi5OAaXF1MBYe06rKWO5TsAwpie3XjM1C7rsKd8pdWaapGB7NkUxzrr0Qf/hnhyiXKrnBG+bMBCn3jSloY2vGcnMJgvq2eUWvAZRwh9vbRWzVPZlP7Dd2EvVHbFl+STBmiPD1rgVg0tJsK7Ou8JGXVpiu4dscfoGR5dbcDdkoCF4og2DymPp13AkamBSFx67NtBSq1eRW/Hcc9VcWayxbbbbR7TTxhJgWFIZZVJpYcXNByvxe8q45Zb4u4BEPAHA==
    database-user: AgDV8xgW9XgKSfHx6kKQardUhSvxrJPlnJQF8JeNHovyduP1PDSBM3RuYWWZe1/AIm4eywlSkiGnd4UH0qGHHQO3E0asqO9TmNLW+e3XFsidnGdi6J6RbNTC6XZRyh2xZO3ab71jXwIbbS1Twf24a36Dep6hEwLMd7aSJonPxtvuIDhdqkPkXQoNrrKZCQO1EMgVnKJedCzWnvRMNYkYgonshczOGQZHQ8PoE5IUSgX4v8y3sv+00mBlQhQJWJ2tYIQ/oh24vesNCiZ3opgZsUF4rKlehnwb3Gl6q4dTSyAc5hOsluYEQXhRViHtSO/NMH0XIHd4xGNnOc2ioF8qD/g8mn5URjFV+3OsoU70q57o/zBeMBjm6zMT/7hfaXSOJjd2eDdBY5F+oPYJwhdLNx9j8PcLI84gzHOmKoXfwZW+LWmC0q4ahoHB+y8AhLxL+wKoDCcVXEHzyVRvsq7289VYYJZoDvctK+vCaID3vG7ra8lR4fLKbkAumLwEv/a4UGEiao1kKfbrbMBwtuqtnpj09drJyX8MO/MVlriPS8xu9rNAzexTpoHgbmKZxRfmcFVUKLrBg8QegOLsZgjxk7Ae5n4iaRB9Id8iQFEFBMDLzh/9dBxSGt48DWRtCv42/Fh07cglsRi3u2yHu9W4n/ZL/vWaE8uW2BiTTn5i0PMOfy6e5dwvQMDhhTmW3i83OiN+toWglA==
  template:
    metadata:
      creationTimestamp: null
      name: database-credentials
      namespace: production
