apiVersion: v1
kind: Service
metadata:
  name: octopub-audit-cluster-ip
spec:
  type: ClusterIP
  selector:
    component: auditservice
  ports:
    - port: 10000
      targetPort: 10000
      name: http-audit
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: octopub-audit-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: auditservice
  template:
    metadata:
      labels:
        component: auditservice
    spec:
      containers:
        - name: auditservice
          image: octopussamples/octopub-audit-microservice-mysql
          ports:
            - name: http-audit
              containerPort: 10000
          env:
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-credentials
                  key: database-password
            - name: DATABASE_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: service-env-vars
                  key: DATABASE_HOSTNAME
            - name: DATABASE_PORT
              valueFrom:
                configMapKeyRef:
                  name: service-env-vars
                  key: DATABASE_PORT
            - name: DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: service-env-vars
                  key: DATABASE_NAME
            - name: DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: database-credentials
                  key: database-user
            - name: MIGRATE_AT_START
              valueFrom:
                configMapKeyRef:
                  name: service-env-vars
                  key: MIGRATE_AT_START
            - name: COGNITO_DISABLE_AUTH
              valueFrom:
                configMapKeyRef:
                  name: service-env-vars
                  key: COGNITO_DISABLE_AUTH