apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
  
resources:
- octopub-audits-mysql.yaml
- octopub-frontend.yaml
- octopub-ingress.yaml
- octopub-products-mysql.yaml

configMapGenerator:
  - name: service-env-vars
    env: variables.properties

generatorOptions:
  disableNameSuffixHash: true